import type { DashboardDefinition } from '@supersubset/schema';

export const defaultDashboard: DashboardDefinition = {
  schemaVersion: '0.2.0',
  id: 'vite-sqlite-dashboard',
  title: 'SQLite Analytics Workbench',
  description: 'A Vite host app that re-queries an in-browser SQLite database based on Supersubset filter state.',
  filters: [
    {
      id: 'filter-region',
      title: 'Region',
      type: 'select',
      fieldRef: 'region',
      datasetRef: 'sqlite-orders',
      operator: 'equals',
      scope: { type: 'global' },
    },
    {
      id: 'filter-category',
      title: 'Category',
      type: 'select',
      fieldRef: 'category',
      datasetRef: 'sqlite-orders',
      operator: 'equals',
      scope: { type: 'global' },
    },
    {
      id: 'filter-date',
      title: 'Order Date',
      type: 'date',
      fieldRef: 'ordered_at',
      datasetRef: 'sqlite-orders',
      operator: 'between',
      scope: { type: 'global' },
    },
  ],
  pages: [
    {
      id: 'overview',
      title: 'Overview',
      rootNodeId: 'root',
      layout: {
        root: { id: 'root', type: 'root', children: ['grid-main'], meta: {} },
        'grid-main': {
          id: 'grid-main',
          type: 'grid',
          parentId: 'root',
          children: ['header-title', 'divider', 'row-kpis', 'row-charts', 'row-table'],
          meta: { columns: 12 },
        },
        'header-title': {
          id: 'header-title',
          type: 'header',
          parentId: 'grid-main',
          children: [],
          meta: { text: 'Local SQLite Analytics', headerSize: 'large' },
        },
        divider: {
          id: 'divider',
          type: 'divider',
          parentId: 'grid-main',
          children: [],
          meta: {},
        },
        'row-kpis': {
          id: 'row-kpis',
          type: 'row',
          parentId: 'grid-main',
          children: ['w-kpi-revenue', 'w-kpi-orders', 'w-kpi-aov'],
          meta: {},
        },
        'w-kpi-revenue': {
          id: 'w-kpi-revenue',
          type: 'widget',
          parentId: 'row-kpis',
          children: [],
          meta: { widgetRef: 'kpi-revenue', width: 4, height: 130 },
        },
        'w-kpi-orders': {
          id: 'w-kpi-orders',
          type: 'widget',
          parentId: 'row-kpis',
          children: [],
          meta: { widgetRef: 'kpi-orders', width: 4, height: 130 },
        },
        'w-kpi-aov': {
          id: 'w-kpi-aov',
          type: 'widget',
          parentId: 'row-kpis',
          children: [],
          meta: { widgetRef: 'kpi-aov', width: 4, height: 130 },
        },
        'row-charts': {
          id: 'row-charts',
          type: 'row',
          parentId: 'grid-main',
          children: ['w-line', 'w-bar'],
          meta: {},
        },
        'w-line': {
          id: 'w-line',
          type: 'widget',
          parentId: 'row-charts',
          children: [],
          meta: { widgetRef: 'chart-monthly-sales', width: 8, height: 360 },
        },
        'w-bar': {
          id: 'w-bar',
          type: 'widget',
          parentId: 'row-charts',
          children: [],
          meta: { widgetRef: 'chart-category-sales', width: 4, height: 360 },
        },
        'row-table': {
          id: 'row-table',
          type: 'row',
          parentId: 'grid-main',
          children: ['w-table'],
          meta: {},
        },
        'w-table': {
          id: 'w-table',
          type: 'widget',
          parentId: 'row-table',
          children: [],
          meta: { widgetRef: 'table-top-products', width: 12, height: 320 },
        },
      },
      widgets: [
        {
          id: 'kpi-revenue',
          type: 'kpi-card',
          title: 'Revenue',
          config: { valueField: 'revenue', comparisonField: 'previousRevenue', format: 'currency', prefix: '$' },
        },
        {
          id: 'kpi-orders',
          type: 'kpi-card',
          title: 'Orders',
          config: { valueField: 'orders', comparisonField: 'previousOrders', format: 'compact' },
        },
        {
          id: 'kpi-aov',
          type: 'kpi-card',
          title: 'Average Order Value',
          config: { valueField: 'aov', comparisonField: 'previousAov', format: 'currency', prefix: '$' },
        },
        {
          id: 'chart-monthly-sales',
          type: 'line-chart',
          title: 'Monthly Revenue + Orders',
          config: {
            xField: 'month',
            yFields: ['revenue', 'orders'],
            smooth: true,
            showLegend: true,
            legendPosition: 'top',
          },
        },
        {
          id: 'chart-category-sales',
          type: 'bar-chart',
          title: 'Revenue by Category',
          config: {
            xField: 'category',
            yFields: ['revenue'],
            showLegend: false,
          },
        },
        {
          id: 'table-top-products',
          type: 'table',
          title: 'Top Products',
          config: { columns: ['product_name', 'units', 'revenue', 'region'] },
        },
      ],
    },
  ],
};