export interface ShipmentPerformanceRow {
  id: number;
  shipped_at: string;
  month: string;
  region: 'North America' | 'Europe' | 'APAC' | 'Latin America';
  hub: string;
  carrier: 'Atlas Air' | 'Horizon Freight' | 'Meridian Cargo';
  lane: string;
  service_level: 'Priority' | 'Standard' | 'Economy';
  revenue: number;
  shipment_count: number;
  delayed_shipments: number;
  on_time_rate: number;
  average_delay_hours: number;
  load_factor: number;
}

export const shipmentPerformanceRows: ShipmentPerformanceRow[] = [
  {
    id: 1,
    shipped_at: '2026-01-08',
    month: 'Jan',
    region: 'North America',
    hub: 'Chicago',
    carrier: 'Atlas Air',
    lane: 'CHI → DEN',
    service_level: 'Priority',
    revenue: 18200,
    shipment_count: 108,
    delayed_shipments: 7,
    on_time_rate: 94.2,
    average_delay_hours: 1.4,
    load_factor: 86.1,
  },
  {
    id: 2,
    shipped_at: '2026-01-12',
    month: 'Jan',
    region: 'Europe',
    hub: 'Rotterdam',
    carrier: 'Horizon Freight',
    lane: 'RTM → BER',
    service_level: 'Standard',
    revenue: 14640,
    shipment_count: 92,
    delayed_shipments: 10,
    on_time_rate: 88.6,
    average_delay_hours: 3.1,
    load_factor: 79.4,
  },
  {
    id: 3,
    shipped_at: '2026-01-18',
    month: 'Jan',
    region: 'APAC',
    hub: 'Singapore',
    carrier: 'Meridian Cargo',
    lane: 'SIN → BNE',
    service_level: 'Priority',
    revenue: 16780,
    shipment_count: 96,
    delayed_shipments: 5,
    on_time_rate: 95.8,
    average_delay_hours: 1.1,
    load_factor: 84.8,
  },
  {
    id: 4,
    shipped_at: '2026-01-24',
    month: 'Jan',
    region: 'Latin America',
    hub: 'Sao Paulo',
    carrier: 'Atlas Air',
    lane: 'GRU → LIM',
    service_level: 'Economy',
    revenue: 12190,
    shipment_count: 84,
    delayed_shipments: 12,
    on_time_rate: 85.4,
    average_delay_hours: 4.2,
    load_factor: 74.3,
  },
  {
    id: 5,
    shipped_at: '2026-02-05',
    month: 'Feb',
    region: 'North America',
    hub: 'Chicago',
    carrier: 'Horizon Freight',
    lane: 'CHI → ATL',
    service_level: 'Standard',
    revenue: 19110,
    shipment_count: 114,
    delayed_shipments: 9,
    on_time_rate: 91.8,
    average_delay_hours: 2.3,
    load_factor: 87.6,
  },
  {
    id: 6,
    shipped_at: '2026-02-11',
    month: 'Feb',
    region: 'Europe',
    hub: 'Rotterdam',
    carrier: 'Meridian Cargo',
    lane: 'RTM → MAD',
    service_level: 'Priority',
    revenue: 15480,
    shipment_count: 95,
    delayed_shipments: 6,
    on_time_rate: 93.6,
    average_delay_hours: 1.6,
    load_factor: 82.5,
  },
  {
    id: 7,
    shipped_at: '2026-02-15',
    month: 'Feb',
    region: 'APAC',
    hub: 'Singapore',
    carrier: 'Atlas Air',
    lane: 'SIN → HKG',
    service_level: 'Standard',
    revenue: 17320,
    shipment_count: 101,
    delayed_shipments: 8,
    on_time_rate: 92.4,
    average_delay_hours: 2.1,
    load_factor: 85.7,
  },
  {
    id: 8,
    shipped_at: '2026-02-22',
    month: 'Feb',
    region: 'Latin America',
    hub: 'Sao Paulo',
    carrier: 'Horizon Freight',
    lane: 'GRU → SCL',
    service_level: 'Economy',
    revenue: 12860,
    shipment_count: 88,
    delayed_shipments: 14,
    on_time_rate: 83.7,
    average_delay_hours: 4.8,
    load_factor: 72.9,
  },
  {
    id: 9,
    shipped_at: '2026-03-04',
    month: 'Mar',
    region: 'North America',
    hub: 'Chicago',
    carrier: 'Meridian Cargo',
    lane: 'CHI → SEA',
    service_level: 'Priority',
    revenue: 20540,
    shipment_count: 118,
    delayed_shipments: 6,
    on_time_rate: 95.1,
    average_delay_hours: 1.2,
    load_factor: 89.3,
  },
  {
    id: 10,
    shipped_at: '2026-03-09',
    month: 'Mar',
    region: 'Europe',
    hub: 'Rotterdam',
    carrier: 'Atlas Air',
    lane: 'RTM → OSL',
    service_level: 'Standard',
    revenue: 14970,
    shipment_count: 90,
    delayed_shipments: 11,
    on_time_rate: 87.9,
    average_delay_hours: 3.4,
    load_factor: 77.8,
  },
  {
    id: 11,
    shipped_at: '2026-03-15',
    month: 'Mar',
    region: 'APAC',
    hub: 'Singapore',
    carrier: 'Horizon Freight',
    lane: 'SIN → NRT',
    service_level: 'Priority',
    revenue: 18460,
    shipment_count: 109,
    delayed_shipments: 7,
    on_time_rate: 94.6,
    average_delay_hours: 1.5,
    load_factor: 88.1,
  },
  {
    id: 12,
    shipped_at: '2026-03-28',
    month: 'Mar',
    region: 'Latin America',
    hub: 'Sao Paulo',
    carrier: 'Meridian Cargo',
    lane: 'GRU → MEX',
    service_level: 'Standard',
    revenue: 13620,
    shipment_count: 93,
    delayed_shipments: 12,
    on_time_rate: 86.2,
    average_delay_hours: 3.7,
    load_factor: 75.8,
  },
  {
    id: 13,
    shipped_at: '2026-04-03',
    month: 'Apr',
    region: 'North America',
    hub: 'Chicago',
    carrier: 'Atlas Air',
    lane: 'CHI → DAL',
    service_level: 'Priority',
    revenue: 21480,
    shipment_count: 121,
    delayed_shipments: 5,
    on_time_rate: 96.3,
    average_delay_hours: 0.9,
    load_factor: 90.2,
  },
  {
    id: 14,
    shipped_at: '2026-04-10',
    month: 'Apr',
    region: 'Europe',
    hub: 'Rotterdam',
    carrier: 'Horizon Freight',
    lane: 'RTM → BCN',
    service_level: 'Economy',
    revenue: 14110,
    shipment_count: 91,
    delayed_shipments: 13,
    on_time_rate: 84.8,
    average_delay_hours: 4.1,
    load_factor: 73.7,
  },
  {
    id: 15,
    shipped_at: '2026-04-18',
    month: 'Apr',
    region: 'APAC',
    hub: 'Singapore',
    carrier: 'Meridian Cargo',
    lane: 'SIN → ICN',
    service_level: 'Standard',
    revenue: 18990,
    shipment_count: 111,
    delayed_shipments: 8,
    on_time_rate: 93.2,
    average_delay_hours: 1.9,
    load_factor: 87.9,
  },
  {
    id: 16,
    shipped_at: '2026-04-25',
    month: 'Apr',
    region: 'Latin America',
    hub: 'Sao Paulo',
    carrier: 'Atlas Air',
    lane: 'GRU → BOG',
    service_level: 'Priority',
    revenue: 13950,
    shipment_count: 97,
    delayed_shipments: 9,
    on_time_rate: 89.4,
    average_delay_hours: 2.9,
    load_factor: 78.5,
  },
  {
    id: 17,
    shipped_at: '2026-05-06',
    month: 'May',
    region: 'North America',
    hub: 'Chicago',
    carrier: 'Horizon Freight',
    lane: 'CHI → PHX',
    service_level: 'Economy',
    revenue: 20870,
    shipment_count: 125,
    delayed_shipments: 11,
    on_time_rate: 90.8,
    average_delay_hours: 2.8,
    load_factor: 88.7,
  },
  {
    id: 18,
    shipped_at: '2026-05-12',
    month: 'May',
    region: 'Europe',
    hub: 'Rotterdam',
    carrier: 'Meridian Cargo',
    lane: 'RTM → DUB',
    service_level: 'Priority',
    revenue: 15820,
    shipment_count: 98,
    delayed_shipments: 6,
    on_time_rate: 94.9,
    average_delay_hours: 1.3,
    load_factor: 83.9,
  },
  {
    id: 19,
    shipped_at: '2026-05-17',
    month: 'May',
    region: 'APAC',
    hub: 'Singapore',
    carrier: 'Atlas Air',
    lane: 'SIN → KUL',
    service_level: 'Economy',
    revenue: 17620,
    shipment_count: 113,
    delayed_shipments: 10,
    on_time_rate: 91.5,
    average_delay_hours: 2.5,
    load_factor: 86.4,
  },
  {
    id: 20,
    shipped_at: '2026-05-26',
    month: 'May',
    region: 'Latin America',
    hub: 'Sao Paulo',
    carrier: 'Horizon Freight',
    lane: 'GRU → UIO',
    service_level: 'Standard',
    revenue: 14410,
    shipment_count: 99,
    delayed_shipments: 13,
    on_time_rate: 85.6,
    average_delay_hours: 4.0,
    load_factor: 76.6,
  },
  {
    id: 21,
    shipped_at: '2026-06-04',
    month: 'Jun',
    region: 'North America',
    hub: 'Chicago',
    carrier: 'Meridian Cargo',
    lane: 'CHI → MIA',
    service_level: 'Priority',
    revenue: 21960,
    shipment_count: 128,
    delayed_shipments: 7,
    on_time_rate: 95.6,
    average_delay_hours: 1.4,
    load_factor: 91.1,
  },
  {
    id: 22,
    shipped_at: '2026-06-11',
    month: 'Jun',
    region: 'Europe',
    hub: 'Rotterdam',
    carrier: 'Atlas Air',
    lane: 'RTM → CPH',
    service_level: 'Standard',
    revenue: 16240,
    shipment_count: 101,
    delayed_shipments: 8,
    on_time_rate: 92.1,
    average_delay_hours: 2.1,
    load_factor: 84.7,
  },
  {
    id: 23,
    shipped_at: '2026-06-19',
    month: 'Jun',
    region: 'APAC',
    hub: 'Singapore',
    carrier: 'Horizon Freight',
    lane: 'SIN → SYD',
    service_level: 'Priority',
    revenue: 19430,
    shipment_count: 116,
    delayed_shipments: 6,
    on_time_rate: 95.2,
    average_delay_hours: 1.0,
    load_factor: 89.5,
  },
  {
    id: 24,
    shipped_at: '2026-06-27',
    month: 'Jun',
    region: 'Latin America',
    hub: 'Sao Paulo',
    carrier: 'Meridian Cargo',
    lane: 'GRU → EZE',
    service_level: 'Economy',
    revenue: 14890,
    shipment_count: 102,
    delayed_shipments: 12,
    on_time_rate: 86.7,
    average_delay_hours: 3.6,
    load_factor: 77.1,
  },
];
